version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.1
    container_name: mailman-core
    hostname: mailman-core
    volumes:
    - /srv/docker-state/mailman3/rootfs/opt/mailman:/opt/mailman
    links:
    - database:database
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:Thahk1zoTh6kaish@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=eiyaikofa7vaawohl7Aezeewaikaizah
    networks:
    - backend

  mailman-web:
    image: maxking/mailman-web:0.1
    container_name: mailman-web
    hostname: mailman.ecobytes.net
    expose:
    - "80"
    - "8000"
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /srv/docker-state/mailman3/rootfs/opt/mailman-web-data:/opt/mailman-web-data
    - ./settings.py:/opt/mailman-web/settings.py
    - ./run.sh:/opt/run.sh
    environment:
    - VIRTUAL_HOST=mailman.ecobytes.net
    - VIRTUAL_PORT=8000
    - LETSENCRYPT_HOST=mailman.ecobytes.net
    - LETSENCRYPT_EMAIL=support@ecobytes.net
    - SERVE_FROM_DOMAIN=mailman.ecobytes.net
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:Thahk1zoTh6kaish@database/mailmandb
    - HYPERKITTY_API_KEY=eiyaikofa7vaawohl7Aezeewaikaizah
    networks:
    - frontend
    - backend

  database:
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: Thahk1zoTh6kaish
    restart: always
    image: postgres:9.6
    volumes:
    - /srv/docker-state/mailman3/rootfs/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
    - backend

networks:
  frontend:
    external:
      name: nginx_default

  backend:
    driver: bridge
